export const IS_ORDER_CANCEL = 'IS_ORDER_CANCEL';
export const LOGIN = 'LOGIN';
export const AUTHENTICATE = 'AUTHENTICATE';
export const LOGOUT = 'LOGOUT';
export const ACCESSTOKEN = 'ACCESSTOKEN';
export const USERPROFILE = 'USERPROFILE';
export const GETFUELS = 'GETFUELS';
export const ORDER_CONFIRM = 'ORDER_CONFIRM';
export const NOTOFICATIONINDICATOR = 'NOTOFICATIONINDICATOR';
export const MESSAGEINDICATOR = 'MESSAGEINDICATOR';
export const ALLNOTIFICATIONS = 'ALLNOTIFICATIONS';

export const GET_CARD = 'GET_CARD';
export const GET_RIDER_COORDINATION = 'GET_RIDER_COORDINATION';
export const RIDESTATUS = 'RIDESTATUS';
export const APPLOADING = 'APPLOADING';
